require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SharingProjectsController do

  # This should return the minimal set of attributes required to create a valid
  # SharingProject. As you add validations to SharingProject, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SharingProjectsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all sharing_projects as @sharing_projects" do
      sharing_project = SharingProject.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sharing_projects).should eq([sharing_project])
    end
  end

  describe "GET show" do
    it "assigns the requested sharing_project as @sharing_project" do
      sharing_project = SharingProject.create! valid_attributes
      get :show, {:id => sharing_project.to_param}, valid_session
      assigns(:sharing_project).should eq(sharing_project)
    end
  end

  describe "GET new" do
    it "assigns a new sharing_project as @sharing_project" do
      get :new, {}, valid_session
      assigns(:sharing_project).should be_a_new(SharingProject)
    end
  end

  describe "GET edit" do
    it "assigns the requested sharing_project as @sharing_project" do
      sharing_project = SharingProject.create! valid_attributes
      get :edit, {:id => sharing_project.to_param}, valid_session
      assigns(:sharing_project).should eq(sharing_project)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SharingProject" do
        expect {
          post :create, {:sharing_project => valid_attributes}, valid_session
        }.to change(SharingProject, :count).by(1)
      end

      it "assigns a newly created sharing_project as @sharing_project" do
        post :create, {:sharing_project => valid_attributes}, valid_session
        assigns(:sharing_project).should be_a(SharingProject)
        assigns(:sharing_project).should be_persisted
      end

      it "redirects to the created sharing_project" do
        post :create, {:sharing_project => valid_attributes}, valid_session
        response.should redirect_to(SharingProject.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sharing_project as @sharing_project" do
        # Trigger the behavior that occurs when invalid params are submitted
        SharingProject.any_instance.stub(:save).and_return(false)
        post :create, {:sharing_project => {}}, valid_session
        assigns(:sharing_project).should be_a_new(SharingProject)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SharingProject.any_instance.stub(:save).and_return(false)
        post :create, {:sharing_project => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sharing_project" do
        sharing_project = SharingProject.create! valid_attributes
        # Assuming there are no other sharing_projects in the database, this
        # specifies that the SharingProject created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SharingProject.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => sharing_project.to_param, :sharing_project => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested sharing_project as @sharing_project" do
        sharing_project = SharingProject.create! valid_attributes
        put :update, {:id => sharing_project.to_param, :sharing_project => valid_attributes}, valid_session
        assigns(:sharing_project).should eq(sharing_project)
      end

      it "redirects to the sharing_project" do
        sharing_project = SharingProject.create! valid_attributes
        put :update, {:id => sharing_project.to_param, :sharing_project => valid_attributes}, valid_session
        response.should redirect_to(sharing_project)
      end
    end

    describe "with invalid params" do
      it "assigns the sharing_project as @sharing_project" do
        sharing_project = SharingProject.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SharingProject.any_instance.stub(:save).and_return(false)
        put :update, {:id => sharing_project.to_param, :sharing_project => {}}, valid_session
        assigns(:sharing_project).should eq(sharing_project)
      end

      it "re-renders the 'edit' template" do
        sharing_project = SharingProject.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SharingProject.any_instance.stub(:save).and_return(false)
        put :update, {:id => sharing_project.to_param, :sharing_project => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sharing_project" do
      sharing_project = SharingProject.create! valid_attributes
      expect {
        delete :destroy, {:id => sharing_project.to_param}, valid_session
      }.to change(SharingProject, :count).by(-1)
    end

    it "redirects to the sharing_projects list" do
      sharing_project = SharingProject.create! valid_attributes
      delete :destroy, {:id => sharing_project.to_param}, valid_session
      response.should redirect_to(sharing_projects_url)
    end
  end

end
